import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { cn } from "@/lib/utils";
import { FloatingNavDemo } from "@/components/ui/nav/FloatingNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
  profile,
}: Readonly<{
  children: React.ReactNode;
  profile: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn( "",`${inter.className}`)}>
        <div className="w-full flex justify-center">
          {/* <Nav></Nav> */}
          <FloatingNavDemo></FloatingNavDemo>
        </div>
          
         {children}
        </body>
    </html>
  );
}